apiVersion: v1
kind: PersistentVolume
metadata:
  name: mnesia-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/data_mnesiac"
